Pertemuan 01 - Pengenalan Data Science
Nama: Athaya Zatus Shawary Lathief
NIM : 250401020181

In [7]:
import pandas as pd

data = {
    "Nama": ["Andi", "Budi", "Citra"],
    "Nilai": [85, 90, 78]
}

df = pd.DataFrame(data)
df

    Nama  Nilai
0   Andi     85
1   Budi     90
2  Citra     78

In [8]:
df.describe()

           Nilai
count   3.000000
mean   84.333333
std     6.027714
min    78.000000
25%    81.500000
50%    85.000000
75%    87.500000
max    90.000000

## Kesimpulan

Pada pertemuan ini saya mempelajari konsep dasar Data Science dan penggunaan DataFrame menggunakan Pandas.

Temuan utama:
- Data dapat disimpan dalam bentuk tabel menggunakan DataFrame.
- Pandas mempermudah analisis data sederhana.

Keterbatasan:
- Dataset yang digunakan masih sangat kecil dan sederhana.